const year = document.getElementById('year');
if (year) year.textContent = new Date().getFullYear();

const revealObserver = new IntersectionObserver((entries) => {
  entries.forEach((entry) => {
    if (entry.isIntersecting) {
      entry.target.classList.add('visible');
      revealObserver.unobserve(entry.target);
    }
  });
}, { threshold: 0.11 });

document.querySelectorAll('.reveal').forEach((el) => revealObserver.observe(el));

const canvas = document.getElementById('cell-field');
const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

if (canvas && !reducedMotion) {
  const ctx = canvas.getContext('2d');
  let width = 0;
  let height = 0;
  let dpr = 1;
  let points = [];
  let mouse = { x: -1000, y: -1000 };

  function resize() {
    dpr = Math.min(window.devicePixelRatio || 1, 2);
    width = window.innerWidth;
    height = window.innerHeight;
    canvas.width = width * dpr;
    canvas.height = height * dpr;
    canvas.style.width = `${width}px`;
    canvas.style.height = `${height}px`;
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);

    const count = Math.min(76, Math.max(34, Math.floor((width * height) / 26000)));
    points = Array.from({ length: count }, () => ({
      x: Math.random() * width,
      y: Math.random() * height,
      vx: (Math.random() - .5) * .12,
      vy: (Math.random() - .5) * .12,
      r: Math.random() * 1.4 + .45,
      phase: Math.random() * Math.PI * 2
    }));
  }

  window.addEventListener('resize', resize, { passive: true });
  window.addEventListener('pointermove', (event) => {
    mouse.x = event.clientX;
    mouse.y = event.clientY;
  }, { passive: true });
  window.addEventListener('pointerleave', () => {
    mouse.x = -1000;
    mouse.y = -1000;
  });

  function frame(t) {
    ctx.clearRect(0, 0, width, height);

    for (const p of points) {
      const dxm = mouse.x - p.x;
      const dym = mouse.y - p.y;
      const dm = Math.hypot(dxm, dym);
      if (dm < 150) {
        p.x -= dxm * .00025;
        p.y -= dym * .00025;
      }

      p.x += p.vx;
      p.y += p.vy;
      if (p.x < -20) p.x = width + 20;
      if (p.x > width + 20) p.x = -20;
      if (p.y < -20) p.y = height + 20;
      if (p.y > height + 20) p.y = -20;
    }

    for (let i = 0; i < points.length; i++) {
      const a = points[i];
      for (let j = i + 1; j < points.length; j++) {
        const b = points[j];
        const dx = a.x - b.x;
        const dy = a.y - b.y;
        const dist = Math.hypot(dx, dy);
        if (dist < 118) {
          ctx.strokeStyle = `rgba(154, 202, 255, ${0.055 * (1 - dist / 118)})`;
          ctx.lineWidth = .65;
          ctx.beginPath();
          ctx.moveTo(a.x, a.y);
          ctx.lineTo(b.x, b.y);
          ctx.stroke();
        }
      }
    }

    for (const p of points) {
      const pulse = .7 + Math.sin(t * .00055 + p.phase) * .25;
      ctx.fillStyle = `rgba(178, 236, 255, ${.18 * pulse})`;
      ctx.beginPath();
      ctx.arc(p.x, p.y, p.r * pulse, 0, Math.PI * 2);
      ctx.fill();
    }

    requestAnimationFrame(frame);
  }

  resize();
  requestAnimationFrame(frame);
}

// Mobile section menu
const menuToggle = document.querySelector('.menu-toggle');
const primaryNav = document.getElementById('primary-nav');

function closeMobileMenu() {
  if (!menuToggle || !primaryNav) return;
  menuToggle.setAttribute('aria-expanded', 'false');
  primaryNav.classList.remove('open');
}

if (menuToggle && primaryNav) {
  menuToggle.addEventListener('click', () => {
    const opening = menuToggle.getAttribute('aria-expanded') !== 'true';
    menuToggle.setAttribute('aria-expanded', String(opening));
    primaryNav.classList.toggle('open', opening);
  });

  primaryNav.querySelectorAll('a').forEach((link) => link.addEventListener('click', closeMobileMenu));
  document.addEventListener('keydown', (event) => {
    if (event.key === 'Escape') closeMobileMenu();
  });
  document.addEventListener('click', (event) => {
    if (!primaryNav.classList.contains('open')) return;
    if (!event.target.closest('.site-header')) closeMobileMenu();
  });
  window.addEventListener('resize', () => {
    if (window.innerWidth > 980) closeMobileMenu();
  }, { passive: true });
}

// Scholar metrics are generated by the scheduled GitHub Action into a static JSON file.
async function loadScholarStats() {
  const citationNode = document.getElementById('scholar-citations');
  const hIndexNode = document.getElementById('scholar-hindex');
  const statusNode = document.getElementById('scholar-status');
  if (!citationNode || !hIndexNode) return;

  try {
    const response = await fetch('assets/scholar-stats.json', { cache: 'no-store' });
    if (!response.ok) return;
    const stats = await response.json();

    const citations = Number(stats.citations);
    const hIndex = Number(stats.h_index);
    if (Number.isFinite(citations)) citationNode.textContent = citations.toLocaleString('en-US');
    if (Number.isFinite(hIndex)) hIndexNode.textContent = hIndex.toLocaleString('en-US');

    if (statusNode && stats.updated_at) {
      const updated = new Date(stats.updated_at);
      if (!Number.isNaN(updated.getTime())) {
        statusNode.textContent = `Google Scholar · updated ${updated.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`;
      }
    }
  } catch (_) {
    // Keep CV fallback values if the generated file is unavailable.
  }
}

loadScholarStats();
